sudo: false
language: csharp
os:
  - linux
  
notifications:
  email: false

branches:
  only:
    - master
    - develop

addons:
  apt:
    packages:
    - zip
    - gzip
    - tar
    - curl

git:
  depth: 9999999

install:
  - nuget restore TS3AudioBot.sln
  - nuget install NUnit.Runners -OutputDirectory nunit

script:
  - cfg="/p:Configuration=Release TS3AudioBot.sln"
  - if command -v msbuild; then
      msbuild $cfg;
    elif command -v xbuild; then
      xbuild $cfg;
    else
      echo "No mono build tool found!";
      false;
    fi
  - mono ./nunit/NUnit.ConsoleRunner.*.*.*/tools/nunit3-console.exe ./TS3ABotUnitTests/bin/Release/TS3ABotUnitTests.dll

after_success:
  - export MAIN_DIR=`pwd`
  - cd ./TS3AudioBot/bin/Release
  - ls
  - 'export version=`mono TS3AudioBot.exe --version | grep "Version: "`'
  - cd "$MAIN_DIR"
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: ./TS3AudioBot/bin/Release/*
  skip_cleanup: true
  on:
    repo: Masyno/TS3AudioBot
    tags: false
    all_branches: true

    
after_script:
  - chmod u+x ts3notify.sh
  - ./ts3notify.sh
