sudo: false
language: csharp
os:
  - linux

notifications:
  email: false

branches:
  only:
    - master
    - develop
  
addons:
  apt:
    packages:
    - zip
    - gzip
    - tar
    - curl

git:
  depth: 9999999

install:
  - nuget restore TS3AudioBot.sln
  - nuget install NUnit.Runners -OutputDirectory nunit

script:
  - cfg="/p:Configuration=Release TS3AudioBot.sln"
  - if command -v msbuild; then
      msbuild $cfg;
    elif command -v xbuild; then
      xbuild $cfg;
    else
      echo "No mono build tool found!";
      false;
    fi
  - mono ./nunit/NUnit.ConsoleRunner.*.*.*/tools/nunit3-console.exe ./TS3ABotUnitTests/bin/Release/TS3ABotUnitTests.dll
  

after_success:
  - export MAIN_DIR=`pwd`
  - cd ./TS3AudioBot/bin/Release
  - zip TS3AudioBot.zip NLog.config * x86/* x64/*
  - "curl --ftp-create-dirs -T TS3AudioBot.zip -u $FTP_USER:$FTP_PASSWORD ftp://kblsystems.de/TS3AudioBot.zip"
  - ls
  - 'export version=`mono TS3AudioBot --version | grep "Version: "`'
  - cd "$MAIN_DIR"

    
after_script:
  - chmod u+x ts3notify.sh
  - ./ts3notify.sh
